# Generated by Django 5.2.6 on 2025-09-13 17:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitFeedback',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('suggestion', 'AI Suggestion'), ('planned_outfit', 'Planned Outfit'), ('worn_outfit', 'Actually Worn'), ('template', 'Template')], default='suggestion', max_length=20)),
                ('outfit_id', models.UUIDField(help_text='ID of the outfit suggestion, plan, or template being rated')),
                ('rating', models.IntegerField(choices=[(-1, 'Thumbs Down'), (0, 'Neutral'), (1, 'Thumbs Up')], help_text='Thumbs up/down rating (-1, 0, 1)')),
                ('star_rating', models.IntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Optional 1-5 star rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Optional user comment about the outfit')),
                ('occasion_context', models.CharField(blank=True, help_text='What occasion the outfit was for', max_length=255)),
                ('outfit_features', models.JSONField(default=dict, help_text='Extracted features from the outfit for ML learning')),
                ('processed_for_learning', models.BooleanField(default=False, help_text='Whether this feedback has been processed for style vector updates')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Outfit Feedback',
                'verbose_name_plural': 'Outfit Feedback',
                'db_table': 'feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='feedback_user_id_8e9eb5_idx'), models.Index(fields=['user', 'rating'], name='feedback_user_id_a39995_idx'), models.Index(fields=['feedback_type'], name='feedback_feedbac_533c89_idx'), models.Index(fields=['processed_for_learning'], name='feedback_process_353a03_idx')],
                'unique_together': {('user', 'outfit_id', 'feedback_type')},
            },
        ),
    ]
