# Generated by Django 5.2.6 on 2025-09-13 17:48

import apps.wardrobe.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('synonyms', models.JSONField(default=list, help_text='List of synonyms for this canonical tag')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Canonical Tag',
                'verbose_name_plural': 'Canonical Tags',
                'db_table': 'canonical_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='User-defined name for the item', max_length=100)),
                ('category', models.CharField(choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('dresses', 'Dresses'), ('outerwear', 'Outerwear'), ('shoes', 'Shoes'), ('accessories', 'Accessories'), ('underwear', 'Underwear'), ('activewear', 'Activewear'), ('formal', 'Formal'), ('sleepwear', 'Sleepwear'), ('other', 'Other')], default='other', max_length=50)),
                ('subcategory', models.CharField(blank=True, help_text='More specific category', max_length=50)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('black', 'Black'), ('white', 'White'), ('grey', 'Grey'), ('beige', 'Beige'), ('navy', 'Navy'), ('maroon', 'Maroon'), ('teal', 'Teal'), ('olive', 'Olive'), ('gold', 'Gold'), ('silver', 'Silver'), ('multicolor', 'Multicolor'), ('other', 'Other')], default='other', max_length=50)),
                ('secondary_color', models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('black', 'Black'), ('white', 'White'), ('grey', 'Grey'), ('beige', 'Beige'), ('navy', 'Navy'), ('maroon', 'Maroon'), ('teal', 'Teal'), ('olive', 'Olive'), ('gold', 'Gold'), ('silver', 'Silver'), ('multicolor', 'Multicolor'), ('other', 'Other')], max_length=50)),
                ('image', models.ImageField(help_text='Main image of the clothing item', upload_to=apps.wardrobe.models.clothing_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail version of the image', upload_to=apps.wardrobe.models.clothing_thumbnail_path)),
                ('cv_confidence', models.FloatField(blank=True, help_text='Confidence score from computer vision classification', null=True)),
                ('cv_metadata', models.JSONField(default=dict, help_text='Additional metadata from computer vision analysis')),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('all_season', 'All Season')], default='all_season', max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('wear_count', models.IntegerField(default=0, help_text='Number of times worn')),
                ('last_worn', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether item is active in wardrobe')),
                ('is_dirty', models.BooleanField(default=False, help_text='Whether item needs washing')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clothing Item',
                'verbose_name_plural': 'Clothing Items',
                'db_table': 'clothing_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(help_text='Tag name (normalized)', max_length=50)),
                ('source', models.CharField(choices=[('user', 'User Added'), ('cv', 'Computer Vision'), ('system', 'System Generated')], default='user', max_length=20)),
                ('confidence', models.FloatField(blank=True, help_text='Confidence score if generated by CV', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='wardrobe.clothingitem')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
            },
        ),
        migrations.AddIndex(
            model_name='clothingitem',
            index=models.Index(fields=['user', 'category'], name='clothing_it_user_id_f610b5_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingitem',
            index=models.Index(fields=['user', 'color'], name='clothing_it_user_id_6b188f_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingitem',
            index=models.Index(fields=['user', 'is_active'], name='clothing_it_user_id_1e208b_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingitem',
            index=models.Index(fields=['user', 'created_at'], name='clothing_it_user_id_e997f1_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingitem',
            index=models.Index(fields=['deleted_at'], name='clothing_it_deleted_9c1eca_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['item'], name='tags_item_id_4a467c_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tag'], name='tags_tag_1fa0e9_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['source'], name='tags_source_0dbc32_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('item', 'tag')},
        ),
    ]
