# Generated by Django 5.2.6 on 2025-10-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='cv_description',
            field=models.TextField(blank=True, help_text='Hidden AI-generated concise description for better recommendations'),
        ),
    ]
